// Export utility for recommendations
import { ChildProfile, ScoredSport, formatHeight } from './scoringEngine';
import { SPORT_CATEGORIES, REGION_NAMES, getRegionFromZip, SportCategory } from './sportsData';

// ============================================================================
// TEXT EXPORT
// ============================================================================

export function exportToText(
  profile: ChildProfile, 
  scoredSports: ScoredSport[], 
  topCount: number = 15
): string {
  const region = getRegionFromZip(profile.zipCode);
  const topSports = scoredSports.slice(0, topCount);
  const date = new Date().toLocaleDateString('en-US', { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  });

  let text = `
╔══════════════════════════════════════════════════════════════════════════════╗
║                    THE LONG GAME - SPORTS ASSESSMENT                          ║
╚══════════════════════════════════════════════════════════════════════════════╝

Generated: ${date}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
ATHLETE PROFILE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Name:                 ${profile.name}
Age:                  ${profile.age} years old
Gender:               ${profile.gender === 'male' ? 'Male' : 'Female'}
Location:             ${profile.zipCode}, ${profile.state} (${REGION_NAMES[region]})
Current Height:       ${formatHeight(profile.currentHeightInches)}
Est. Adult Height:    ${profile.estimatedAdultHeightInches ? formatHeight(profile.estimatedAdultHeightInches) : 'Not calculated'}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
TOP ${topCount} RECOMMENDED SPORTS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

`;

  topSports.forEach((scored, index) => {
    const { sport, scores, weightedTotal, ageMatchNote, heightAdvantageNote } = scored;
    const category = SPORT_CATEGORIES[sport.category as SportCategory];
    
    text += `
┌─────────────────────────────────────────────────────────────────────────────┐
│  #${(index + 1).toString().padStart(2, '0')}  ${sport.name.padEnd(40)} Score: ${weightedTotal}/100  │
└─────────────────────────────────────────────────────────────────────────────┘

  Category:       ${category.name}
  Timing:         ${ageMatchNote}
  Ideal Start:    ${sport.idealStartAge.min}-${sport.idealStartAge.max} years

  SCORES:
    Fun Factor:    ${scores.funFactor}/10
    Skill Focus:   ${scores.skillFocus}/10
    Competition:   ${scores.competition}/10  (higher = less competitive locally)
    Opportunity:   ${scores.opportunity}/10
    Accessibility: ${scores.accessibility}/10

  COSTS:
    Entry Level:   $${sport.costRange.entryLevel.min.toLocaleString()}-$${sport.costRange.entryLevel.max.toLocaleString()}/year
    Competitive:   $${sport.costRange.competitive.min.toLocaleString()}-$${sport.costRange.competitive.max.toLocaleString()}/year

  OUTLOOK:
    College Opp:   ${'★'.repeat(sport.collegeOpportunity)}${'☆'.repeat(5 - sport.collegeOpportunity)}
    Lifespan:      ${'★'.repeat(sport.lifespanValue)}${'☆'.repeat(5 - sport.lifespanValue)}

${heightAdvantageNote && heightAdvantageNote !== "Add estimated adult height for personalized opportunity score" ? `  HEIGHT NOTE:   ${heightAdvantageNote}\n` : ''}
  ${sport.notes}

`;
  });

  text += `
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SCORING FACTORS EXPLAINED
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Fun Factor      How enjoyable and engaging the sport typically is for youth
Skill Focus     Emphasis on technical skill development
Competition     Inverse of local competition level (higher = more opportunity)
Opportunity     Physical/height advantage based on predicted adult height
Accessibility   Combination of cost, equipment needs, and local availability

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Generated by The Long Game | Youth Sports Assessment Tool
https://thelonggame.app

`;

  return text;
}

// ============================================================================
// CSV EXPORT
// ============================================================================

export function exportToCSV(
  _profile: ChildProfile, 
  scoredSports: ScoredSport[]
): string {
  // Header
  let csv = 'Rank,Sport,Category,Score,Fun,Skill,Competition,Opportunity,Accessibility,';
  csv += 'Age Match,Ideal Start Age,Entry Cost Min,Entry Cost Max,Competitive Cost Min,Competitive Cost Max,';
  csv += 'College Opportunity,Lifespan Value,Height Note\n';
  
  // Data rows
  scoredSports.forEach((scored, index) => {
    const { sport, scores, weightedTotal, ageMatch, heightAdvantageNote } = scored;
    const category = SPORT_CATEGORIES[sport.category as SportCategory];
    
    const row = [
      index + 1,
      `"${sport.name}"`,
      `"${category.name}"`,
      weightedTotal,
      scores.funFactor,
      scores.skillFocus,
      scores.competition,
      scores.opportunity,
      scores.accessibility,
      ageMatch,
      `${sport.idealStartAge.min}-${sport.idealStartAge.max}`,
      sport.costRange.entryLevel.min,
      sport.costRange.entryLevel.max,
      sport.costRange.competitive.min,
      sport.costRange.competitive.max,
      sport.collegeOpportunity,
      sport.lifespanValue,
      `"${heightAdvantageNote || ''}"`
    ];
    
    csv += row.join(',') + '\n';
  });
  
  return csv;
}

// ============================================================================
// DOWNLOAD HELPERS
// ============================================================================

export function downloadFile(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  link.style.display = 'none';
  try {
    document.body.appendChild(link);
    link.click();
  } finally {
    if (link.parentNode) {
      document.body.removeChild(link);
    }
    URL.revokeObjectURL(url);
  }
}

export function downloadTextReport(profile: ChildProfile, scoredSports: ScoredSport[]): void {
  const content = exportToText(profile, scoredSports);
  const filename = `${profile.name.replace(/\s+/g, '_')}_sports_assessment_${new Date().toISOString().split('T')[0]}.txt`;
  downloadFile(content, filename, 'text/plain');
}

export function downloadCSVReport(profile: ChildProfile, scoredSports: ScoredSport[]): void {
  const content = exportToCSV(profile, scoredSports);
  const filename = `${profile.name.replace(/\s+/g, '_')}_sports_data_${new Date().toISOString().split('T')[0]}.csv`;
  downloadFile(content, filename, 'text/csv');
}

// ============================================================================
// HTML/PRINT EXPORT (for PDF via browser print)
// ============================================================================

export function generatePrintableHTML(
  profile: ChildProfile, 
  scoredSports: ScoredSport[], 
  topCount: number = 15
): string {
  const region = getRegionFromZip(profile.zipCode);
  const topSports = scoredSports.slice(0, topCount);
  const date = new Date().toLocaleDateString('en-US', { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  });

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Sports Assessment - ${profile.name}</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700&display=swap');
    
    * { box-sizing: border-box; margin: 0; padding: 0; }
    
    body {
      font-family: 'Outfit', sans-serif;
      color: #1e293b;
      line-height: 1.5;
      padding: 40px;
      max-width: 800px;
      margin: 0 auto;
    }
    
    .header {
      text-align: center;
      margin-bottom: 30px;
      padding-bottom: 20px;
      border-bottom: 3px solid #10b981;
    }
    
    .header h1 {
      font-size: 28px;
      color: #10b981;
      margin-bottom: 5px;
    }
    
    .header .subtitle {
      color: #64748b;
      font-size: 14px;
    }
    
    .profile-section {
      background: #f8fafc;
      padding: 20px;
      border-radius: 12px;
      margin-bottom: 30px;
    }
    
    .profile-section h2 {
      font-size: 16px;
      color: #64748b;
      margin-bottom: 15px;
      text-transform: uppercase;
      letter-spacing: 1px;
    }
    
    .profile-grid {
      display: grid;
      grid-template-columns: repeat(3, 1fr);
      gap: 15px;
    }
    
    .profile-item {
      background: white;
      padding: 12px;
      border-radius: 8px;
    }
    
    .profile-item .label {
      font-size: 11px;
      color: #94a3b8;
      text-transform: uppercase;
    }
    
    .profile-item .value {
      font-size: 16px;
      font-weight: 600;
    }
    
    .sport-card {
      border: 1px solid #e2e8f0;
      border-radius: 12px;
      margin-bottom: 15px;
      page-break-inside: avoid;
    }
    
    .sport-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      padding: 15px;
      background: #f8fafc;
      border-radius: 12px 12px 0 0;
    }
    
    .sport-rank {
      width: 36px;
      height: 36px;
      background: #10b981;
      color: white;
      border-radius: 50%;
      display: flex;
      align-items: center;
      justify-content: center;
      font-weight: 700;
      font-size: 14px;
    }
    
    .sport-name {
      flex: 1;
      margin-left: 12px;
    }
    
    .sport-name h3 {
      font-size: 18px;
      margin-bottom: 2px;
    }
    
    .sport-name .category {
      font-size: 12px;
      color: #64748b;
    }
    
    .sport-score {
      text-align: right;
    }
    
    .sport-score .number {
      font-size: 28px;
      font-weight: 700;
      color: #10b981;
    }
    
    .sport-score .label {
      font-size: 10px;
      color: #94a3b8;
      text-transform: uppercase;
    }
    
    .sport-body {
      padding: 15px;
    }
    
    .scores-grid {
      display: grid;
      grid-template-columns: repeat(5, 1fr);
      gap: 8px;
      margin-bottom: 15px;
    }
    
    .score-item {
      text-align: center;
      padding: 8px;
      background: #f8fafc;
      border-radius: 8px;
    }
    
    .score-item .value {
      font-size: 18px;
      font-weight: 600;
      color: #1e293b;
    }
    
    .score-item .label {
      font-size: 10px;
      color: #94a3b8;
    }
    
    .sport-details {
      display: grid;
      grid-template-columns: repeat(2, 1fr);
      gap: 10px;
      font-size: 13px;
    }
    
    .detail-item {
      display: flex;
      justify-content: space-between;
    }
    
    .detail-item .label {
      color: #64748b;
    }
    
    .footer {
      margin-top: 40px;
      text-align: center;
      color: #94a3b8;
      font-size: 12px;
      padding-top: 20px;
      border-top: 1px solid #e2e8f0;
    }
    
    @media print {
      body { padding: 20px; }
      .sport-card { break-inside: avoid; }
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>🏅 The Long Game</h1>
    <div class="subtitle">Youth Sports Assessment Report • ${date}</div>
  </div>
  
  <div class="profile-section">
    <h2>Athlete Profile</h2>
    <div class="profile-grid">
      <div class="profile-item">
        <div class="label">Name</div>
        <div class="value">${profile.name}</div>
      </div>
      <div class="profile-item">
        <div class="label">Age</div>
        <div class="value">${profile.age} years</div>
      </div>
      <div class="profile-item">
        <div class="label">Gender</div>
        <div class="value">${profile.gender === 'male' ? 'Male' : 'Female'}</div>
      </div>
      <div class="profile-item">
        <div class="label">Location</div>
        <div class="value">${profile.state} (${REGION_NAMES[region]})</div>
      </div>
      <div class="profile-item">
        <div class="label">Current Height</div>
        <div class="value">${formatHeight(profile.currentHeightInches)}</div>
      </div>
      <div class="profile-item">
        <div class="label">Est. Adult Height</div>
        <div class="value">${profile.estimatedAdultHeightInches ? formatHeight(profile.estimatedAdultHeightInches) : 'N/A'}</div>
      </div>
    </div>
  </div>
  
  <h2 style="margin-bottom: 20px; font-size: 18px;">Top ${topCount} Recommended Sports</h2>
  
  ${topSports.map((scored, index) => {
    const { sport, scores, weightedTotal, ageMatchNote } = scored;
    const category = SPORT_CATEGORIES[sport.category as SportCategory];
    return `
    <div class="sport-card">
      <div class="sport-header">
        <div class="sport-rank">${index + 1}</div>
        <div class="sport-name">
          <h3>${sport.name}</h3>
          <div class="category">${category.name}</div>
        </div>
        <div class="sport-score">
          <div class="number">${weightedTotal}</div>
          <div class="label">Score</div>
        </div>
      </div>
      <div class="sport-body">
        <div class="scores-grid">
          <div class="score-item">
            <div class="value">${scores.funFactor}</div>
            <div class="label">Fun</div>
          </div>
          <div class="score-item">
            <div class="value">${scores.skillFocus}</div>
            <div class="label">Skill</div>
          </div>
          <div class="score-item">
            <div class="value">${scores.competition}</div>
            <div class="label">Comp</div>
          </div>
          <div class="score-item">
            <div class="value">${scores.opportunity}</div>
            <div class="label">Opp</div>
          </div>
          <div class="score-item">
            <div class="value">${scores.accessibility}</div>
            <div class="label">Access</div>
          </div>
        </div>
        <div class="sport-details">
          <div class="detail-item">
            <span class="label">Timing:</span>
            <span>${ageMatchNote.split(' - ')[0]}</span>
          </div>
          <div class="detail-item">
            <span class="label">Ideal Start:</span>
            <span>${sport.idealStartAge.min}-${sport.idealStartAge.max} years</span>
          </div>
          <div class="detail-item">
            <span class="label">Entry Cost:</span>
            <span>$${sport.costRange.entryLevel.min}-$${sport.costRange.entryLevel.max}/yr</span>
          </div>
          <div class="detail-item">
            <span class="label">College Opp:</span>
            <span>${'★'.repeat(sport.collegeOpportunity)}${'☆'.repeat(5 - sport.collegeOpportunity)}</span>
          </div>
        </div>
      </div>
    </div>
    `;
  }).join('')}
  
  <div class="footer">
    Generated by The Long Game • Youth Sports Assessment Tool<br>
    Scores are personalized recommendations based on child profile and family priorities.
  </div>
</body>
</html>
  `;
}

export function openPrintableReport(profile: ChildProfile, scoredSports: ScoredSport[]): boolean {
  const html = generatePrintableHTML(profile, scoredSports);
  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    alert('Unable to open print window. Please check if popups are blocked and try again.');
    return false;
  }
  printWindow.document.write(html);
  printWindow.document.close();
  // Delay print to allow styles to load
  setTimeout(() => {
    printWindow.print();
  }, 500);
  return true;
}
